#! /bin/bash

# Author: Jacob Hillebrand
# Incepted: 11/06/2018
# Description: This is a simple terminal program that will
#	allow a user to keep a to-do list. The user can call 
#	the script with parameters like "list", "clear","add",
#	and "remove" to interact with the list.

# Declare variables
ACTION=$1

# Perform requested operation
case "$1" in
	list) python ~/Terminal_To_Do-master/list_action.py
		;;
	clear) python ~/Terminal_To_Do-master/clear_action.py
		;;
	add) python ~/Terminal_To_Do-master/add_action.py
		;;
	remove) python ~/Terminal_To_Do-master/remove_action.py
		;;
	help) echo "Welcome to Terminal_To_Do! Try typing ttd <op> to get started:"
		echo "	Args:"
		echo "		list 	- lists all to-do items"
		echo "		clear 	- clears the to-do list"
		echo "		add 	- allows you to enter another item to your list"
		echo "		remove 	- allows you to remove a specific item from your list"
		echo "		help 	- shows this :)"
		;;
	*) echo "ttd: Command not found. Try \"help\" param for help"
		;;
esac
